import { StyleSheet, Dimensions } from "react-native";

const width = Dimensions.get("window").width;
const height = Dimensions.get("window").height;
const isBig = 700 < height;

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
  },
  flexible: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-evenly",
    alignItems: "center",
    width: "100%",
    padding: 40,
  },
  textPrimary: {
    fontSize: 21,
    color: "#5733d1",
    fontFamily: "FredokaLight",
  },
  input: {
    width: "80%",
    height: 34,
    color: "#000",
    borderRadius: 10,
    backgroundColor: "#f1f1f1",
    paddingLeft: 20,
    fontFamily: "FredokaLight",
    marginTop: 10,
    marginBottom: 10,
  },
  button: {
    width: "40%",
    height: 34,
    borderRadius: 10,
    backgroundColor: "#5733d1",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 10,
    marginBottom: 10,
  },
  transfer: {
    width: "120%",
    height: 45,
    borderRadius: 10,
    backgroundColor: "#ebebeb",
    display: "flex",
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    marginTop: 8,
    marginBottom: 8,
  },
  tab: {
    width: "50%",
    height: 50,
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    borderBottomWidth: 2,
  },
  cardastro: {
    width: "90%",
    height: "25%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "space-around",
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 10,
    marginTop: 20,
    shadowColor: "#ccc",
    marginLeft: "5%",
  },
  maphistory: {
    width: "90%",
    height: "45%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "flex-start",
    backgroundColor: "#fff",
    borderRadius: 20,
    marginTop: 20,
    shadowColor: "#ccc",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
    elevation: 0,
  },
  flex: {
    width: "100%",
    height: "10%",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
  },
  safearea: {
    flex: 1,
    width: width,
    display: "flex",
    alignItems: "center",
  },
  searchView: {
    width: "90%",
    height: 40,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    backgroundColor: "#fff",
    borderRadius: 10,
    paddingLeft: (width / 100) * 5,
    marginTop: isBig ? 20 : 10,
  },
  columnFlex: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "space-around",
    marginTop: 10,
  },
  rowFlex: {
    width: "100%",
    display: "flex",
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "flex-start",
    marginLeft: "10%",
  },
  modal: {
    width: "100%",
    height: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#fff",
    padding: 20,
    shadowColor: "#ccc",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
    elevation: 3,
  },
  whiteButton: {
    width: "90%",
    height: isBig ? 40 : 35,
    backgroundColor: "#fff",
    display: "flex",
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    paddingLeft: 10,
  },
});
